### ISSUE TITLE
can I run this over network and play multiplayer with my friends?

### ISSUE THREAD

**Issue by cyberhck** [theKidOfArcrania/BlocklyIO#15]

**Comment by theKidOfArcrania** [comment]
Yes you can definitely do that! Thanks for asking beforehand. As long as if you use this code, that you would still link back to this repo, and just give due credit for me!

**Comment by cyberhck** [comment]
I'm just planning to play locally, I won't even make modifications or change it in any way, just want to play during scrums :) I'll probably modify you html file to include a link to this repo if I'm able to figure out, and everyone who's playing will know any way because I don't want to be the only one who's hosting, so they'll need to clone this repo as well :)

All I need is my friends to be able to play with me multiplayer.

**Comment by theKidOfArcrania** [comment]
Nah you're totally fine :)

I'm just talking about there's a person who I think took my code, monetized it and then dunno if he actually credited me... :(

**Comment by cyberhck** [comment]
don't worry, I wouldn't do that.
