### ISSUE TITLE
Add WASD

### ISSUE THREAD

**Issue by tylerolson** [theKidOfArcrania/BlocklyIO#5]
Arrow keys aren't very intuitive. WASD is though :)

**Comment by theKidOfArcrania** [comment]
Hmm lol okay I'll see about adding wasd support sometime soon

**Comment by tylerolson** [comment]
I'm making a clone myself could you help me out with the land gaining algorithm? My email is tolson519@gmail.com

**Comment by MrRefactoring** [comment]
implemented it https://github.com/theKidOfArcrania/BlocklyIO/pull/11
